// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoPooBuses.Database;

#nullable disable

namespace ProyectoPooBuses.Migrations
{
    [DbContext(typeof(BusUseRegisterDbContext))]
    [Migration("20260413231033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ProyectoPooBuses.Entities.BusRegisterEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BusModel")
                        .HasColumnType("TEXT")
                        .HasColumnName("bus_model");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dni");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("route_number");

                    b.HasKey("Id");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("ProyectoPooBuses.Entities.RouteRegisterEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BusId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bus_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hour");

                    b.Property<int>("TotalPassengers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_passenger");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("ProyectoPooBuses.Entities.TotalDailyStatisticsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("MostUsedRoute")
                        .HasColumnType("TEXT")
                        .HasColumnName("most_used_route");

                    b.Property<int>("OffPeakHour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("off_peak_hour");

                    b.Property<int>("RushHour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rush_hour");

                    b.Property<int>("TotalPassengersDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_passenger_day");

                    b.HasKey("Id");

                    b.ToTable("Dailies");
                });

            modelBuilder.Entity("ProyectoPooBuses.Entities.RouteRegisterEntity", b =>
                {
                    b.HasOne("ProyectoPooBuses.Entities.BusRegisterEntity", "Bus")
                        .WithMany("Routes")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("ProyectoPooBuses.Entities.BusRegisterEntity", b =>
                {
                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
